model CONVERTER
  Dynawo.Electrical.Controls.Basics.Step PREF() ;
  Dynawo.Electrical.Controls.Basics.Step QREF() ;
  Converter3 converter() ;
  CurrentLoop3 currentloop() ;
  Measurements measurements() ;
  OuterLoop2 outerloop() ;
equation
  connect(outerloop.Pref,PREF.step.value) ;
  connect(outerloop.Qref,QREF.step.value) ;
  connect(converter.idConv,measurements.id) ;
  connect(converter.iqConv,measurements.iq) ;
  connect(measurements.omega,converter.omegaPu) ;
  connect(measurements.theta,converter.theta) ;
  connect(currentloop.vdref,converter.vdConv) ;
  connect(converter.vdFilter,measurements.vd) ;
  connect(currentloop.vqref,converter.vqConv) ;
  connect(converter.vqFilter,measurements.vq) ;
  connect(measurements.idr,currentloop.id) ;
  connect(outerloop.idref,currentloop.idref) ;
  connect(measurements.iqr,currentloop.iq) ;
  connect(outerloop.iqref,currentloop.iqref) ;
  connect(measurements.omega,currentloop.omegaPu) ;
  connect(measurements.vdr,currentloop.vd) ;
  connect(measurements.vqr,currentloop.vq) ;
  connect(outerloop.id,measurements.idr) ;
  connect(outerloop.iq,measurements.iqr) ;
  connect(measurements.omega,outerloop.omegaPu) ;
  connect(outerloop.vq,measurements.vqr) ;
end CONVERTER;
